run:
    - GTX750Ti-CDP
    - GTX750Ti-PTXPLUS-CDP

GTX750Ti-CDP:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX750Ti-CDP/gpgpusim.config"
    extra_params: " -gpgpu_cdp_enabled 1 \n -gpgpu_max_concurrent_kernel 32 \n -gpgpu_local_mem_map 0 \n -gpgpu_concurrent_kernel_sm 1 \n -gpgpu_kernel_launch_latency 100 \n -cdp_latency 0,0,0,0,0 \n -gpgpu_deadlock_detect 1"

GTX750Ti-PTXPLUS-CDP:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX750Ti-CDP/gpgpusim.config"
    extra_params: " -gpgpu_ptx_convert_to_ptxplus 1 \n -gpgpu_cdp_enabled 1 \n -gpgpu_max_concurrent_kernel 32 \n -gpgpu_local_mem_map 0 \n -gpgpu_concurrent_kernel_sm 1 \n -gpgpu_kernel_launch_latency 100 \n -cdp_latency 0,0,0,0,0 \n -gpgpu_deadlock_detect 1"
