dist: xenial

before_install:
    - docker pull accelsim/ubuntu-18.04_cuda-11:latest

language: cpp


matrix:
  include:
    - services: docker
      env:
        - CUDA_INSTALL_PATH=/usr/local/cuda-11.0

script:
    - docker run -v `pwd`:/accel-sim:rw accelsim/ubuntu-18.04_cuda-11:latest /bin/bash travis.sh
