dist: xenial

before_install:
    - docker pull accelsim/ubuntu-18.04_cuda-11:latest

language: cpp


matrix:
  include:
    - services: docker
      env:
        global:
            - CUDA_INSTALL_PATH=/usr/local/cuda-11.0
            - DOCKER_IMAGE=accelsim/ubuntu-18.04_cuda-11:latest

script:
    - docker run -v `pwd`:/accel-sim:rw $DOCKER_IMAGE /bin/bash travis.sh
