# Basefile Configs

# Pascal
GTX1080Ti:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX1080Ti/gpgpusim.config"

# Deorecated files in the public repo
QUADROFX5600:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5600/gpgpusim.config"

QUADROFX5800:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5800/gpgpusim.config"

TESLAC2050:
    base_file: "$GPGPUSIM_ROOT/configs/TeslaC2050/gpgpusim.config"

GTX480:
    base_file: "$GPGPUSIM_ROOT/configs/GTX480/gpgpusim.config"

# This is a smaller GPU that takes forever to simulate
GTX750Ti:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX750Ti/gpgpusim.config"

# Our Internal configurations
3.x_PASCALTITANX:
    base_file: "$GPGPUSIM_ROOT/configs/PascalTitanX/gpgpu-sim-3.x/gpgpusim.config"

P100_HBM:
    base_file: "$GPGPUSIM_ROOT/configs/Pascal-P100-HBM/gpgpusim.config"

TITANX_P102:
    base_file: "$GPGPUSIM_ROOT/configs/Pascal-P102-GDDR5X/gpgpusim.config"

# Extra configs - these are composable.
# The names here will be appended to the basefile name with hyphens
#   For example TITANX_P102-L1ON-PTXPLUS
PTXPLUS:
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

L1ON:
    extra_params: "-gmem_skip_L1D 0"

COPYK:
    extra_params: "-perf_sim_memcpy 1"

2B:
    extra_params: "-gpgpu_max_insn 2000000000"

1B:
    extra_params: "-gpgpu_max_insn 2000000000"


# Experimental - for SM 60 PTXplus support
PTXPLUS_SM6:
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 62 -gpgpu_ptx_force_min_capability 60"


