run:
    - GTX480
    - QUADROFX5600
    - QUADROFX5800
    - TESLAC2050
    - GTX750Ti

GTX480:
    base_file: "$GPGPUSIM_ROOT/configs/GTX480/gpgpusim.config"
    extra_params: "-gpgpu_max_insn 1000000000"

GTX480-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/GTX480/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 \n -gpgpu_max_insn 1000000000"

QUADROFX5600:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5600/gpgpusim.config"
    extra_params: "-gpgpu_max_insn 1000000000"

QUADROFX5600-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5600/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 \n -gpgpu_max_insn 1000000000"

QUADROFX5800:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5800/gpgpusim.config"
    extra_params: "-gpgpu_max_insn 1000000000"

QUADROFX5800-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/QuadroFX5800/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 \n -gpgpu_max_insn 1000000000"

TESLAC2050:
    base_file: "$GPGPUSIM_ROOT/configs/TeslaC2050/gpgpusim.config"
    extra_params: "-gpgpu_max_insn 1000000000"

TESLAC2050-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/TeslaC2050/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 \n -gpgpu_max_insn 1000000000"

GTX750Ti:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX750Ti/gpgpusim.config"
    extra_params: "-gpgpu_max_insn 1000000000"

GTX750Ti-PTXPLUS:
    base_file: "$GPGPUSIM_ROOT/configs/GeForceGTX750Ti/gpgpusim.config"
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 \n -gpgpu_max_insn 1000000000"
